\NeedsTeXFormat{LaTeX2e}
\ProvidesClass{aac-table}[2018/03/27 Tables for Cashner monograph]
\LoadClass{book}
\RequirePackage{fontspec}
\setmainfont{Libertinus Serif}
\RequirePackage[margin=1in]{geometry}
\RequirePackage{tabulary}
\RequirePackage{booktabs}
\RequirePackage{microtype}
\RequirePackage[document]{ragged2e}
\setlength{\RaggedRightParindent}{0pt}
\setlength{\parindent}{0pt}
\pagestyle{empty}
\endinput
